
# This example passes viewbridge params via command line input.
# The `--watch` flag will monitor file changes and update as needed.
viewbridge:
	viewbridge -d views/ -e hogan -o public/javascripts/templates.js -x .hjs --watch

